### ISSUE TITLE
Properties vs. Environment Variables

### ISSUE THREAD

**Issue by jtarsha** [cyberark/conjur-api-java#17]
ReadMe at [https://github.com/cyberark/conjur-api-java] says 4 *environment* variables are required, however Endpoints class is using System.getProperty on CONJUR_APPLIANCE_URL and CONJUR_ACCOUNT, which will not search environment variables and will return Null instead. Result is a malformed URI. Either the code should be changed to use System.getenv or the instructions should be modified.

**Comment by AndrewCopeland** [comment]
This can be closed since it was resolved in https://github.com/cyberark/conjur-api-java/pull/43.
now system properties and environment variables can be used for configuration.

**Comment by sgnn7** [comment]
This is confirmed fixed in the current v2.2.0 release. Readme will be updated too with #70. Closing.
