### ISSUE TITLE
authenticate fails due to a missing timestamp on the returned auth token

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur-api-java#19]
Tim Fleming reported this issue.

He did something like this:
```
Conjur conjur = new Conjur(username, pass);
cojur.variables().retrieveSecret('password');
```
Instead of getting the secret, he gets a Java.Lang.NullPointerException because the `timestamp` field is not set in the token. This is related to a recent change in the token format.

To resolve this issue, the library should change to tolerate a missing `timestamp` field.

**Comment by dustinmm80** [comment]
This has been addressed with release https://github.com/cyberark/conjur-api-java/releases/tag/v2.0.0
