### ISSUE TITLE
Library has been updated to work against Conjur V4 & Conjur V5 

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-api-java#20]
Library should support the Conjur V4 api w/ the environment variable `CONJUR_VERSION` set to `4`.  By default, the library should support the V5 API specification: https://www.conjur.org/api.html

**Comment by dustinmm80** [comment]
This has been addressed with release https://github.com/cyberark/conjur-api-java/releases/tag/v2.0.0
