### ISSUE TITLE
NullPointerException returned 

### ISSUE THREAD

**Issue by AndrewCopeland** [cyberark/conjur-api-java#41]
NullPointerException is returned if any of the configuration environment variables are not provided.
We should return an informative exception with what environment variables are missing.

**Comment by micahlee** [comment]
This can also be caused when a JAX-RS implementation is not available, as one is not provided in the shaded jar.

The README currently says that Apache CXF is used by default, but we should document that this needs to be obtained and included in the classpath if not using maven.

For example:
```
java -cp ".:conjur-api-2.1.0-with-dependencies.jar:cxf-core-3.3.5.jar" \
  -DCONJUR_AUTHN_LOGIN=host/my-host \
  -DCONJUR_AUTHN_API_KEY=... \
  -DCONJUR_APPLIANCE_URL=https://conjur.my-company.net \
  -DCONJUR_ACCOUNT=demo \
  Example
```

**Comment by AndrewCopeland** [comment]
Resolved in: https://github.com/cyberark/conjur-api-java/pull/43
