### ISSUE TITLE
Readme has been updated to include Maven instructions

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-api-java#50]
It's come to light that the current Readme is missing instructions to include publication to Maven.  Ofira has created a PR (#47) which includes an improvement to the JAR build.  What's missing from the Readme is the process of adding the JAR to Maven.

Ofira has graciously added a demo in the `conjurdemos/conjur-intro`. This includes all the steps required to load the JAR into Maven: https://github.com/conjurdemos/conjur-intro/pull/46/files#diff-604246ad4ac58e848e36bf01aac10f04.

Using @oburstein-hub's branch (`OCP_installer_and_java_test`) as the base, please add the Maven instructions to the project `Readme`.

**Comment by jvanderhoof** [comment]
Please reach out to JFC via Slack (@jf christophe) for questions.

**Comment by h-artzi** [comment]
The Maven publication instructions have been added. Please let me know if anything needs to be changed

**Comment by jf** [comment]
> Please reach out to JFC via Slack (@jf christophe) for questions.

eh, no. How am I involved here?

**Comment by JfcAtCyberArk** [comment]
> > Please reach out to JFC via Slack (@jf christophe) for questions.
> 
> eh, no. How am I involved here?

Sorry, looks like there has been a name conflict between GitHub and Slack :)
