### ISSUE TITLE
javadoc compiling problem

### ISSUE THREAD

**Issue by eltony81** [cyberark/conjur-api-java#57]
Hi,
I have an error during the compilation of conjur-api (master branch): it seems param serviceID does not match the param in constructor signature:

Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JavaDocs report generation:
Exit code: 1 - C:\Users\antonio.di.fluri\Documents\Unicredit_PULS\DevDocs\conjur-api-java\src\main\java\net\conjur\api\Conjur.java:30: error: @param name not found
     * @param serviceID service for authenticating to Conjur
              ^
C:\Users\antonio.di.fluri\Documents\Unicredit_PULS\DevDocs\conjur-api-java\src\main\java\net\conjur\api\Conjur.java:32: warning: no @param for authnUrl
    public Conjur(String username, String password, String authnUrl) {
           ^

**Comment by izgeri** [comment]
Hello @eltony81 - we've made some updates just now in #59 that should address that error. Can you try again after pulling the new code and let us know whether this resolves the problem you're seeing too?

**Comment by eltony81** [comment]
Thanks

It works with maven 3 and jdk 8 (with jdk11 there are the wellknown problem
with modules)

Cheers

Il Gio 12 Mar 2020, 16:26 Geri Jennings <notifications@github.com> ha
scritto:

**Comment by izgeri** [comment]
Great! Thanks for flagging this for us - since it's resolved, I'll close this issue now.
