### ISSUE TITLE
README updated for v2.2.0 release

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur-api-java#70]
## Overview

The [v2.2.0](https://github.com/cyberark/conjur-api-java/releases/tag/v2.2.0) release included a number of great fixes/additions that were implemented in PR #43: 

> * Properties will be retrieved from system properties and if not found will then be retrieved from environment variables. Resolves issue: #17
> * If a mandatory property (CONJUR_ACCOUNT, CONJUR_APPLIANCE_URL) is not provided a more verbose exception message will be thrown instead of a NullPointerException. Resolves issue: #41
> * Allows the ability to supply an authentication service ID, this will allow alternative authentication methods to use this client library such as authn-iam and authn-oidc. Resolves issue: #40

However, the README wasn't updated to help users take advantage of these changes.  Today, @AndrewCopeland was kind enough to add mention of these features in PRs #66 and #67.  In this way, users will be aware that they exist, but I would like us to take this a step further and provide some detailed guidance, as described in the sections below.

## 1. System Property Configuration

According to Andrew, the code to support configuration via system properties has been around for quite some time, but was broken.  Additionally, the README never mentioned it.  So essentially this "bug" is really a new feature for users.  Please update the "Configuration" section of the README to address the following points/questions:

* Very brief explanation (or at least link to explaining Java doc) about what system properities are.
* Example(s) of providing a config value via a system property, ideally via command line option and via Maven.
* Precedence rules for environment variables vs properties.
* Warning to avoid storing sensitive config values (like API key) in source controlled system property files.

## 2. Alternative Authentication Methods

This versions add support for setting the `CONJUR_AUTHN_URL` configuration value in order to use a different authentication method.  Please update the "Configuration" and likely the "Authorization Examples" section of the README to address these points/questions:

* Clearly state what the default authentication method is, if this value isn't set.
* Describe how providing this value might affect the use of other configuration values.
* Provide at least once example of configuring the API with this value.

**Comment by alexkalish** [comment]
@sgnn7: Please add me as a second review to the PR.  Thanks.

**Comment by izgeri** [comment]
@AndrewCopeland do you have any insight for (2)? in particular, it would help us if you could share an example of configuring the API using the alternate authn-url value

**Comment by sgnn7** [comment]
@alexkalish / @izgeri Alrighty - this is finally in a state where I can say that it's ready: https://github.com/cyberark/conjur-api-java/pull/71
