### ISSUE TITLE
Enable setting custom SSLContext for TLS connection to Conjur server

### ISSUE THREAD

**Issue by vvidovic** [cyberark/conjur-api-java#74]
## I would like to be able to dynamically set TLS trust to Conjur server
I would like to be able to dynamically set up TLS trust between application using conjur-api-java library and Conjur server to simplify the setup of the application using conjur-api-java in k8s environment.

## Enable setting SSL Context when initializing the Conjur class instance

I would be able to set up proper trust between my application and Conjur server from k8s configmap and/or secret configurations.

## Alternative is to configure Java VM cacerts

I find current solution with Java VM configuration a bit more hard to do.

Similar to issue [Support for Reading SSL Certs from an Environment Variable](https://github.com/cyberark/conjur-api-java/issues/24)

**Comment by izgeri** [comment]
This was released in https://github.com/cyberark/conjur-api-java/releases/tag/v3.0.0 - closing this issue now :)
