### ISSUE TITLE
There is a new major release of the Java client

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-java#83]
In #82 we're adding Maven publishing to the project, which will break the standard import path for this library as we change its prefix from `net` to `com.cyberark`.

In #82, we add change log entries to describe this change and add an UPGRADING.md (that is referenced in the change log) to describe the custom upgrade process for this change.

In this card, we will bump the project version to 3.0.0 and tag a new release, which will be the first release to publish this project to Maven.

AC:
- [x] Follow the [release instructions](https://github.com/cyberark/conjur-api-java/blob/master/CONTRIBUTING.md#releasing) to create a new `v3.0.0` tag in the project

**Comment by BradleyBoutcher** [comment]
Release has been created and published
[Upgrading instructions](https://github.com/cyberark/conjur-api-java/blob/master/UPGRADING.md) 
[OSSRH Artifacts](https://oss.sonatype.org/#nexus-search;quick~com.cyberark)
